"""empty message

Revision ID: 4e97201c8bcc
Revises: 
Create Date: 2019-10-04 10:06:09.357189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e97201c8bcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robot_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_model_description'), 'robot_model', ['description'], unique=False)
    op.create_index(op.f('ix_robot_model_uuid'), 'robot_model', ['uuid'], unique=False)
    op.create_table('robotcommand_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commandId', sa.Integer(), nullable=True),
    sa.Column('commandDescription', sa.String(length=64), nullable=True),
    sa.Column('commandName', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('robot_uuid', sa.String(length=64), nullable=True),
    sa.Column('created_command', sa.DateTime(), nullable=True, load_only=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robotcommand_model_commandDescription'), 'robotcommand_model', ['commandDescription'], unique=False)
    op.create_index(op.f('ix_robotcommand_model_commandId'), 'robotcommand_model', ['commandId'], unique=False)
    op.create_index(op.f('ix_robotcommand_model_commandName'), 'robotcommand_model', ['commandName'], unique=False)
    op.create_index(op.f('ix_robotcommand_model_robot_uuid'), 'robotcommand_model', ['robot_uuid'], unique=False)
    op.create_index(op.f('ix_robotcommand_model_value'), 'robotcommand_model', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robotcommand_model_value'), table_name='robotcommand_model')
    op.drop_index(op.f('ix_robotcommand_model_robot_uuid'), table_name='robotcommand_model')
    op.drop_index(op.f('ix_robotcommand_model_commandName'), table_name='robotcommand_model')
    op.drop_index(op.f('ix_robotcommand_model_commandId'), table_name='robotcommand_model')
    op.drop_index(op.f('ix_robotcommand_model_commandDescription'), table_name='robotcommand_model')
    op.drop_table('robotcommand_model')
    op.drop_index(op.f('ix_robot_model_uuid'), table_name='robot_model')
    op.drop_index(op.f('ix_robot_model_description'), table_name='robot_model')
    op.drop_table('robot_model')
    # ### end Alembic commands ###
