version: "3.7"

services:
  pg-database:
    # image: kameri/devicedb:v1.0
    image: kameri/devicedb:v1.0
    # deploy:
    #   endpoint_mode: dnsrr    
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgresql.conf:/etc/postgresql.conf
    environment:
      - POSTGRES_DB=devicedb
      - POSTGRES_PASSWORD=device
      - POSTGRES_USER=device
    networks:
      - net
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "5432:5432"
    # command: postgres -c tcp_keepalives_idle=60 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=60

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  net:

volumes:
  db-data:
